# How to setup danger with github actions: https://www.jessesquires.com/blog/2020/04/10/running-danger-on-github-actions/

name: Check leaks
run-name: ${{ github.actor }} is checking for leaks 🚀
on: [pull_request]
jobs:
  Explore-Github-Actions:
    runs-on: macos-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v4
      
      - uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: 14.2.0

      - name: ruby versions
        run: |
          ruby --version
          gem --version
          bundler --version

      - name: ruby setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - run: xcodebuild -project MemoryLeaksCheck.xcodeproj -scheme MemoryLeaksCheck -destination 'platform=iOS Simulator,name=iPhone 14 Pro' CONFIGURATION_BUILD_DIR=$PWD/build

      - uses: mobile-dev-inc/action-maestro-cloud@v1.1.1
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: build/MemoryLeaksCheck.app

      # - name: danger
      #   env:
      #     DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
      #   run: bundle exec danger --dangerfile=Dangerfile.leaksReport --danger_id=LeaksReport

      - run: echo "🍏 This job's status is ${{ job.status }}."